default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["BOOK_TRACKER_DATABASE_USERNAME"] %>
  password: <%= ENV["BOOK_TRACKER_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: book_tracker_api_development

test:
  <<: *default
  database: book_tracker_api_test

production:
  <<: *default
  database: book_tracker_api_production
  url: <%= ENV["DATABASE_URL"] %>
